# fly.toml app configuration file generated for kinger on 2023-09-05T17:58:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kinger"
primary_region = "cdg"

[build]
  image = "mrpatrek/kinger:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="djtl3pslr"
  CloudinarySettings__ApiKey="876652364218522"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
